image: node:16.3

stages:
    - test
    - compile

ESLinter:
    stage: test
    script:
        - npm i
        - node ./node_modules/eslint/bin/eslint.js src/
    cache:
        key: ${CI_COMMIT_BRANCH}
        paths:
            - node_modules

Compile:
    stage: compile
    script:
        - yarn install
        - yarn compile
    cache:
        key: ${CI_COMMIT_BRANCH}
        paths:
            - node_modules
